apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name.cms }}-service-lb
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.name.cms }}-deploy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: {{ .Values.nodePort.cms }}
