apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecam-ingress
  namespace: {{ .Values.nameSpace }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
        - path: {{ .Values.ingressPath.img }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.name.cms }}-service-lb
              port:
                number: 80
        - path: {{ .Values.ingressPath.cms }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.name.cms }}-service-lb
              port:
                number: 80
        - path: {{ .Values.ingressPath.app }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.name.app }}-service-lb
              port:
                number: 80
