apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name.app }}-deploy
spec:
  selector:
    matchLabels:
      app: {{ .Values.name.app }}-deploy
  template:
    metadata:
      name: {{ .Values.name.app }}
      labels:
        app: {{ .Values.name.app }}-deploy
    spec:
      containers:
      - image: {{ .Values.image.app }}
        imagePullPolicy: Always
        name: {{ .Values.name.app }}-con
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: db-connections
              key: database-uri
        - name: REDIS_URI
          valueFrom:
            secretKeyRef:
              name: db-connections
              key: redis-uri
        - name: STREAM_URL
          valueFrom:
            configMapKeyRef:
              name: envs-ecam-app
              key: stream-server-url
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: envs-ecam-app
              key: kafka-brokers
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - mountPath: {{ .Values.mountPath.app }}
          name: {{ .Values.name.app }}-vol
      volumes:
      - name: {{ .Values.name.app }}-vol
        persistentVolumeClaim:
          claimName: {{ .Values.pvcName }}
  replicas: {{ .Values.replicaCount.app }}
