apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name.cms }}-deploy
spec:
  selector:
    matchLabels:
      app: {{ .Values.name.cms }}-deploy
  template:
    metadata:
      name: {{ .Values.name.cms }}
      labels:
        app: {{ .Values.name.cms }}-deploy
    spec:
      containers:
      - image: {{ .Values.image.cms }}
        imagePullPolicy: Always
        name: {{ .Values.name.cms }}-con
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: {{ .Values.mountPath.cms }}
          name: {{ .Values.name.cms }}-vol
      volumes:
      - name: {{ .Values.name.cms }}-vol
        persistentVolumeClaim:
          claimName: {{ .Values.pvcName }}
  replicas: {{ .Values.replicaCount.cms }}